Document: pin-debian-main
Title: Debian pin-debian-main Manual
Author: <insert document author here>
Abstract: This manual describes what pin-debian-main is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pin-debian-main/pin-debian-main.sgml.gz

Format: postscript
Files: /usr/share/doc/pin-debian-main/pin-debian-main.ps.gz

Format: text
Files: /usr/share/doc/pin-debian-main/pin-debian-main.text.gz

Format: HTML
Index: /usr/share/doc/pin-debian-main/html/index.html
Files: /usr/share/doc/pin-debian-main/html/*.html
